blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://ascillato.github.io/VSCode-Logger/
    about: All the information related to this VSCode Extension.
  - name: Discussions and Support
    url: https://github.com/ascillato/VSCode-Logger/discussions
    about: Usage Questions, Feature Requests and Projects.
